### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/drupal4gov.us#2]
Can we get a simple splash page up based on the design you already made? With just a link to drupalgovcon.org and a link to the google group?

It's going to take me some time to understand Acquia hosting... and I just don't have a lot of time right now. But I would like to be able to at least link back to something... ya know?

**Comment by timwood** [comment]
Seems like a good idea. Once Jon builds something I can either help you work with the Acquia environment to publish it or I/Jon can do it. Since we only have the WXT code in that Acquia account/repo we can just get rid of that (or use Git branching to move it aside), delete the database and add the static files. We can review whatever we commit at http://drupal4govdev.prod.acquia-sites.com/ initially and once we are happy we just drag it over to the Stage and then Prod environment using this screen https://insight.acquia.com/cloud/workflow?s=2079886.

Last step is to configure DNS for drupal4gov.us to point to our Acquia production environment IP address. The production environment is already set to respond to that hostname, DNS is just not pointing to it yet. You can see this at https://insight.acquia.com/cloud/domains?s=2079886

The IP address that drupal4gov.us (and www) should point to is 107.21.104.61

**Comment by jonraedeke** [comment]
It would be great to get some input on text for the D4G splash. I'm just not sure what all needs to be said.

@jdearie is this the design you were referring too?

![d4g_branding](https://cloud.githubusercontent.com/assets/2054715/5912960/5e49834a-a5a9-11e4-859f-07515ac0e473.png)

**Comment by jdearie** [comment]
Yep - that's the one. I started an google doc a ways back to start putting together content... 

https://docs.google.com/document/d/1s32vFnAU2pxtniDJsUv4EOAjfSVP1v4Rlfd-p9_8vaI/edit?usp=sharing

I have a few ideas, but I like this tag line the best so far:

Connecting and serving government employees committed to open source technology

That same folder (drupal4gov) also has some draft outlines for content... but if we just have the page in place with the slogan it's a start.

Should we/can we link to the google group? https://groups.google.com/forum/#!forum/us-government-drupalers

**Comment by jdearie** [comment]
What do you think about installing Wet and just having the site design not be as awesome right away?  I'm starting to understand how to get stuff on and around the hosting enviro - but most of what i'll be doing will be configuration of the site and creating content page. From what I can tell - most of what we will be using is built into Wet. It's a matter of turning modules on and configuring them.

I started playing on the Wet install on dev, but we really need to do an update. It's still running 7.31 core.

I feel like if I have a site to publish content to, i'm more likely to get stuff online.  We can modify and add to content as we have time... but the basics should be easy enough to get started with.

Thoughts?

**Comment by jonraedeke** [comment]
I say give it a shot and if we run into issues, I can do the static thing.

**Comment by onelittlebecca** [comment]
This is outdated. We have a basic d7 site up so will update in new issue with theme design and dev -- closing this issue.
